### ISSUE TITLE
Data Collection

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/axelrod-moran#17]
### Validation data

- [x] 1000 repetitions

### Cache of match outcomes

- [x] 1000 repetitions

### N, i = N, 1

- [x] N = 2
- [x] N = 3
- [x] N = 4
- [x] N = 5
- [x] N = 6
- [x] N = 7
- [x] N = 8
- [x] N = 9
- [x] N = 10
- [x] N = 11
- [x] N = 12
- [x] N = 13
- [x] N = 14

### N, i = N, N / 2

Standard

- [x] N = 2
- [x] N = 4
- [x] N = 6
- [x] N = 8
- [x] N = 10
- [x] N = 12
- [x] N = 14

~~Noise (including here even though we discussed not going in to the paper)~~ EDIT: Removing them so things look nicer.

**Comment by marcharper** [comment]
We could include the odd N for (1, N-1) -- it would make the median plots a bit more full, and would illustrate the N > 2 transition better. What do you think?

**Comment by drvinceknight** [comment]
> What do you think?

:+1: Got them running (still in the LIGO queue) :)

**Comment by drvinceknight** [comment]
FYI, I'm ticking these off when they've finished being collected on the cluster (not necessarily up to date in our dropbox folder).

**Comment by drvinceknight** [comment]
FYI, I expect this'll be complete if not in a couple of days by the end of the week :fireworks: :+1:

**Comment by drvinceknight** [comment]
Un-ticking all those tick boxes made me weep a bit inside... :laughing:

**Comment by marcharper** [comment]
It will be worth it :)

**Comment by drvinceknight** [comment]
:+1: :D

**Comment by drvinceknight** [comment]
This is not a drill! All data is collected! Not a drill :)
