### ISSUE TITLE
Fix an Axelrod version

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/axelrod-moran#2]
@marcharper I'm finally coming back to this. 

Should we re run all the results with a fixed Axelrod version? Say 1.16? (That's the latest one)

I'll throw a requirements.txt file together for this repo.

**Comment by drvinceknight** [comment]
I had missed `strategies.py` so I see you have fixed the strategies. Still happy with those?

**Comment by marcharper** [comment]
Agreed on fixing the version.

I excluded some strategies because they are time consuming to generate data for, but we can certainly revisit the list.

**Comment by drvinceknight** [comment]
> I excluded some strategies because they are time consuming to generate data for, but we can certainly revisit the list.

I'm happy with the current list, I guess the main thing would be to check that we aren't missing out any recent additions that are particularly interesting.

**Comment by marcharper** [comment]
I'll take a look. There are some cheap strategies that have been added recently; I think we should try to get MetaHunter, my new ensemble, and maybe a few others in the final set. But let's fine tune the other parameters on the faster to generated collection and then see where we're at.
