### ISSUE TITLE
Discussion from #19

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/axelrod-moran#20]
> Here's my take on the relative fitness narrative -- if you don't think it's sufficient we can leave it out. Generally the literature looks at whether a strategy fixates with a probability higher than a neutral mutant as a judge of whether it's better than the opponent. In most explicit cases this seems to imply that the player would also win at other starting points (i, N-i), but as the examples I sent via email show, the reality is more complicated. We can explain it either by showing that x_i - i/N isn't always the same sign, or we can use the effective relative fitness and say it depends on i. Additionally the values of r_i show how much a strategy benefits (or is hurt) by having a larger subpopulation -- for TFT vs defector r_i is increasing in i, but for ZDExtort it's not since it doesn't play well against itself. To me, r_i is an easier quantity to think about than phi_i.

The sticking point in my mind is not the value of r_i but the way we are calculating them. In my mind this seems to be:

1. At the start of the paper: we demonstrate that the fixation is pop distribution dependent.
2. We then say let's assume that's not true which means the fixation probability is given as a function of a constant relative fitness which we can numerically invert.
3. Let's make conclusions based on that.

But it seems that there's a weakness there in how we calculate the r_i. If I was a reviewer I would definitely question this: we're presenting a number that we have spent all the paper saying is not correct.

**But** perhaps I'm missing something. I think this is good to talk about.

Things that seem fishy

> Table 4: The top strategies list shuffles in a way that I wouldn't expect. Could it be noise in the fixation probabilities?

Possibly, I'm not sure.

> Tables 6 and 7 are too similar -- seems unbelievable

The first 5 rows are exactly the same but the first five rows are ranked based on performance in N=2 (note the values of 1, 2, 3, 4, 5 in the N=2 column) so they should be the same. The last fives rows are different because they correspond to how the strategies are ranked in N=12 (note the values of 1, 2, 3, 4, 5 in the last column). This is what we would expected.

> Figure 11 doesn't agree with the tables presented above -- for example see Collective Strategy, it should be near the top throughout

- [x] I'm not sure what's going on here, I'll take another look.

> Figures 12 and 13 are off as well -- the lines from left to right do not appear to be correct. For example Collective strategy on the left doesn't run to CS on the right. Many of the strategies on the right don't have any line into them.

I believe that this is because of the draws: all strategies on the right do have lines going to them but they are aggregated together because of draws so they do not appear in a helpful position.

Could also be due to some data still being missing.

> Figure 16 (d) -- the strategies are neutral so the plot is just the computational noise. Same for (g)

Yup, these are just thrown in as is, I've seen your points later down about drawing specific things I'll get on that :+1:

> We claim that 1000 outcomes is enough for the approximate process since the max unique outcomes is less than 1000, but the distribution matters as well, right? Not all the outcomes are equally likely.

Yup the distribution mattering is a very good point.

> Things I vote to change or remove:

> We should use the standard abbreviations of the strategies after the first use -- TFT, CS for Collective Strategy, etc.

- [x] Good idea. I'll throw a function with some abbreviations at the top of the notebook.

> ? rm Table 2

- [x] Cool.

> For figures 3 and, it may be better to have plots where a single strategy is up against several others, plotting x_1 for each (and 1/N for comparison), and separate plots for x_{N/2} and x_{N-1}.
> For figure 3 the strategy choices are good -- I suggest Defector versus Defector, Alternator, Cooperator, TFT, and WSLS, with i/N plotted as the reference line as described above.

- [ ] Yup.

> For Figure 4 I suggest: Cooperator, Random, the top ZD, GTFT, Worse and Worse 2. This removes some of the lesser known strategies and prevents us from having to explain them, and also should be a better validation for readers familiar with the common strategies

- [ ] Yup.

> We should use "short names" without the parameters in the tables and figures (but keep the parameters in the strategy list at the end)

- [x] And perhaps put any abbreviations in the strategy list.

> Figure 6: In figure 6 (b) is the more interesting, so we should give it the full width. I recommend leaving off plot (a). In general the plots are too compressed. I vote to remove the Moran diagram (the lower one in figure 6). The diagram in the introduction is sufficient IMO.

- [x] I completely agree :) 

> Figures 8 and 10 -- I think we should consider dividing by (1 / N) to center the plots uniformly

I'm not strongly against this although I feel that there is (small) value in showing that the probabilities move as expected when N changes.

> Figure 14 / Table 9: Maybe just the heatmaps for x_1 and x_{N-1} are sufficient to make the point that the N=2 ranks don't correlate well with the higher ranks

I'm easy, there's an argument that the tables are relatively clear and present all the information (we could shade the cells too). But the plots look pretty.

> Re: the analytical formula for fixations, it would work if we instead estimated transition probabilities directly rather than use an average fitness. It's not practically any easier but the current framing misses this nuance.

I'm not sure I follow what you are suggesting we do here but I think it's related to the discussion about relative fitness so let's chat about that in one go.

> Finally, an important discussion point. If we used mean instead of median for the fixation plots is the result very different? I know I used median originally but mean may be better since it's a better generalization of how effective a strategy is overall at invading or defending. This is an important choice since it changes the order of "best" in some cases -- some distributions are very skewed. This may also explain the FSM players since they were trained to maximize the mean, and they skew rightward more in the plots.

- [x] Yeah: great point. I'll re run with mean (it's a minor fix), I'll have this ready for whenever we chat.

**Comment by drvinceknight** [comment]
Thanks for all the comments: looking good, feels like progress :+1:

**Comment by marcharper** [comment]
Sounds like we're mostly on the same page :)

Re: relative fitness, neutrality is determined by phi_i = i/N or r_i = 1 since there is a bijection between phi_i and r_i from [0, 1] to [0, \infty) (different for each i). It's just easier for me to think in terms of relative fitnesses being different from 1, and to use the frequency independent formula as a comparison object. For example, some strategies are more fit in a group and we can see that because r_j > r_1 > 1, which is easier than phi_j / (j/N) > phi_1 / (1 / N) > 1 -->  phi_j / j > phi_1 > 1/N.

Perhaps there's not enough value here to include this in the paper, we can make all the same points using just phi_i.

> I believe that this is because of the draws: all strategies on the right do have lines going to them but they are aggregated together because of draws so they do not appear in a helpful position.

I'm not sure I understand this -- a can see a few ties but it seems unlikely that so many strategies would have the exact same median (and so the same rank). Maybe it's just the data as you say and will clear up.

Re: the analytical fixation formula, you can derive it for an arbitrary two-type birth-death in terms of the transition probabilities between states (Formula 9). This works for any choice of nonzero transition probabilities. For the deterministic case the transition probabilities come from of the fitness landscape (Formulas 6-8), which is hard to compute exactly in general because of stochastic nature of some of the strategies. However the transition probabilities could be empirically computed to a high degree of approximation without factoring through fitness. The factorization adds error since the fitness landscape may have a lot of variance and using just the mean may give poorer results.

I'm not suggesting we change the calculations, just that the explanation of why the analytic formula isn't a good approximation in the manuscript passes over this point (and so feels like a bit of a strawman).

**Comment by drvinceknight** [comment]
> since there is a bijection between phi_i and r_i from [0, 1] to [0, \infty) (different for each i).  It's just easier for me to think in terms of relative fitnesses being different from 1, and to use the frequency independent formula as a comparison object.

That's already cleared it up a bit in my head: we're not saying it is the relative fitness just that it's a thing that can be spoken about in the same way as the relative fitness... Either way I think once we have a chat we'll know where we want to go with this.

> I'm not sure I understand this -- a can see a few ties but it seems unlikely that so many strategies would have the exact same median (and so the same rank). Maybe it's just the data as you say and will clear up.

Yes this seems suspicious. I'll make sure it's completely cleared up.

**Comment by drvinceknight** [comment]
> Yes this seems suspicious. I'll make sure it's completely cleared up.

It's the mean/median! With a median it is completely understandable that there is a large number of ties:

With median:

```python
>>> df = pd.DataFrame(main.groupby(["player", "N"])["$p_1$"].median()).reset_index()
>>> df = df.pivot(index="player", columns="N", values="$p_1$").reset_index()
>>> df[2].nunique()
46
>>> df[12].nunique()
46
```

With mean:

```python
>>> df = pd.DataFrame(main.groupby(["player", "N"])["$p_1$"].mean()).reset_index()
>>> df = df.pivot(index="player", columns="N", values="$p_1$").reset_index()
>>> df[2].nunique()
164
>>> df[12].nunique()
164
```

:)

**Comment by drvinceknight** [comment]
The plots were complete upside down (but the axes weren't): fixing now.

**Comment by marcharper** [comment]
Cool! Glad that's sorted :)

**Comment by drvinceknight** [comment]
@marcharper  #23 addresses the points I've ticked off here. For the validation graphs: I'm going to need to run more data, just to confirm:

- For deterministic: we want one graph with Defector as the `player` and the opponent being one of each: Defector, Alternator, Cooperator, TFT, and WSLS, (So there will be Defector v Defector there?). Then repeat that for a total of 3 times (x_1, x_{N/2} and x_{N-1}).

- For stochastic: same as above but can you clarify the strategy match ups please?

Thus for we will have a total of 6 graphs.

**Comment by marcharper** [comment]
Defector vs defector in the first should be neutral so I think it makes sense. Cooperator and TFT should be less and more fit, respectively.

For the second: I was thinking Cooperator versus Random, the top ZD (extort-2?), GTFT, and Worse and Worse 2. I tried to pick some well-known stochastic strategies and WaW2 since it's in some of the tables and not as well-known. We can pick others if you'd like.


Are we sure it was just mean vs median? The median fixation probabilities should have been floating point values, right? So they should have almost never been exactly equal.

**Comment by drvinceknight** [comment]
> For the second: I was thinking Cooperator versus Random, the top ZD (extort-2?), GTFT, and Worse and Worse 2. I tried to pick some well-known stochastic strategies and WaW2 since it's in some of the tables and not as well-known. We can pick others if you'd like.

No that all sounds fine: was just checking I had understood correctly :+1: Will get that done (although WaW2 has disappeared from the tables since moving to mean).

> 
> Are we sure it was just mean vs median? The median fixation probabilities should have been floating point values, right? So they should have almost never been exactly equal.

I'm 99.5% sure, looking at the data there were in fact only 46 unique values for the median fixation probabilities (which in turn explains the high number of ties). I think that's what we see when we look at the old box plots (the current ones have moved to median) where we see a large number of strategies have median fixation probability 0. I expect that's a number of strategies who just collapse against each other. Let me know if you're not convinced by that and I will pull out data and investigate further.

**Comment by drvinceknight** [comment]
For the stochastic strategies I think I'll not do Cooperator vs the opponents but Random vs the opponents. I think that'll show more divergence from the theoretic model. (I can always run more and try a  bunch etc...).

**Comment by marcharper** [comment]
Those strategies sound good, and the new plots are looking much better -- awesome to see the ML strategies do so well, especially for larger N.

For the additional FSM players it looks like we're not using the right initial state -- the default is 1 but our strategies should be starting at state 0. We missed that on the copy-paste of the transitions :( ... I should have started them at 1 probably. Anyway what's happening is that the handshakes are misaligned and they are turning into ALLD, which is why they do well at N=2 and not well for N>2.

I'd expect the median fixation probability to be closer to 1/N since that's what all the mutually cooperating strategies would have. Still seems unlikely that we'd hit that on the nose -- for n repetitions and neutral competitors we're essentially sampling from a binomial with mean p=1/N, for the match outcomes. However the mean plots conform to my expectations so I think I'm missing something here.

**Comment by drvinceknight** [comment]
> For the additional FSM players it looks like we're not using the right initial state -- the default is 1 but our strategies should be starting at state 0. We missed that on the copy-paste of the transitions :( ... I should have started them at 1 probably. Anyway what's happening is that the handshakes are misaligned and they are turning into ALLD, which is why they do well at N=2 and not well for N>2.

Oh no! Dammit... 

Is it this line in `players.py`:

```python
 47 fsm_players = [axl.FSMPlayer(transitions=transitions)                                                                                             
 48                for transitions in fsm_transitions]  
```

Should that in fact be:

```python
 47 fsm_players = [axl.FSMPlayer(transitions=transitions, initial_state=1)                                                                                             
 48                for transitions in fsm_transitions]  
```

I can get those extra ones running if we feel it's worth it. Shouldn't be too complicated are time consuming... Once I've got the cached outcomes built for them it should be straightforward because of the caching.

**Comment by drvinceknight** [comment]
> we're essentially sampling from a binomial with mean p=1/N, for the match outcomes.

Good point. I'll investigate some more.

**Comment by marcharper** [comment]
PR: #24

**Comment by drvinceknight** [comment]
I've got the cache running again for the missing players.

**Comment by drvinceknight** [comment]
That was fast. Done, getting all the results running again. Note that I've kept the bunk FSM players in for now (makes no difference to data collection about from the 9 matchups between the new and bunk ones). We can always throw them out once we've got all the data in.

**Comment by drvinceknight** [comment]
@marcharper there's a small issue with how the Moran process handles `Defector` vs `Defector` or similar, mathematically the probability will indeed be $$i/N$$ but in the implemented `MoranProcess` we just pick out the first strategy as the winner, so the probability is always 1. I don't think that's a big issue, just that we want to think about how we present that and if indeed we show the results for `Defector` vs `Defector` and similar. Here's one of the plots (just with 50 repetitions for now - will improve legend placement etc...):

![download 11](https://cloud.githubusercontent.com/assets/2131546/25865286/5435e952-34ea-11e7-8474-5a55de9901ee.png)

**Comment by drvinceknight** [comment]
Here are a couple more (now tidied up etc):

![download 12](https://cloud.githubusercontent.com/assets/2131546/25866783/84791cec-34ef-11e7-9fd1-281ac76bee08.png)


![download 13](https://cloud.githubusercontent.com/assets/2131546/25866786/86f2c996-34ef-11e7-9113-c538ac05c522.png)

It's still early (this is just with 50 repetitions as opposed to 1000 that are currently running) but I'm not convinced this is better than what is currently there: I thing the 2 grids of 3 by 3 plots showed things more clearly. Let me know what you think.

**Comment by drvinceknight** [comment]
It might just be that 5 is too much... Here are some with just 3:

![download 15](https://cloud.githubusercontent.com/assets/2131546/25867440/73d32480-34f1-11e7-95c0-40e11099e2de.png)
![download 14](https://cloud.githubusercontent.com/assets/2131546/25867445/74d3aec2-34f1-11e7-9ee2-0189b283bc27.png)

(The legend markers are off there because of the numbers: ignore it for now.)

Let's wait and see what it all looks like when we've got the new full validation data.

**Comment by marcharper** [comment]
I like the plots with three curves each; we can leave off the neutral plots. Thanks for generating these.

**Comment by drvinceknight** [comment]
> I like the plots with three curves each; we can leave off the neutral plots. Thanks for generating these.

I'm still not completely sure these illustrate things better but let's chat about that later: I've generated all of them now with the full set of 1000 repetitions. :+1:

**Comment by drvinceknight** [comment]
Closing this, I think we've covered everything.
