### ISSUE TITLE
Memory length for the 3 trained FSMs

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/axelrod-moran#25]
This corresponds to the longest cycle + the length of the longest path to that cycle. Once #22 is finished it might be simpler to see this from the images.

Once that's done we'll need to hard code the memory in `./src/players.py` and run the analysis again (for the tables/plots about memory).

**Comment by marcharper** [comment]
Maybe it's max_b(max_p path length of paths p from starting state to state b)? I guess there has to be at least one cycle.

**Comment by drvinceknight** [comment]
In the paper I think you wrote 

>For example,                                                                
>  a strategy that utilizes a handshaking mechanism where the opponents actions                                                                    
> on the first few rounds of play determines the strategies subsequent behavior                                                                   
> would have infinite memory depth.             

That would indicate that the memory length can be unbounded? (Some of our FSMs have a handshake)

**Comment by marcharper** [comment]
Yeah I guess it's more complex -- if it's possible to return to the initial state then it's not unbounded. But for the hard-coded handshake mechanisms in the library that's not the case.

**Comment by drvinceknight** [comment]
In #30 I've gone with `float(inf)` for the two strategies with the the handshake and I think I've put 16 down for the other one (that's a terrible guess as it actually only has 8 states). Something to fix before we submit.
