### ISSUE TITLE
Archiving the data

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/axelrod-moran#27]
I would like to put the data on Zenodo so that it is properly archived with a DOI etc.

I suggest the following "packages":

- Package 1: Raw Moran process data:
    - To include the cache
    - To include the actual raw simulation data
    - To include `players.csv`

- Package 3: The processed data (`main.csv`) everything that is being used  for the analysis
    - To include `main.csv`
    - To include `fixation_validation.csv`

@marcharper do you want us to include another package with the data from #26 or would you just like that to be under version control?

**Comment by marcharper** [comment]
We can put it all together. I put it under version control for safe keeping.

**Comment by drvinceknight** [comment]
:+1:

**Comment by drvinceknight** [comment]
> We can put it all together.

I agree, in #30 I've put a place holder for the Zenodo reference.

**Comment by drvinceknight** [comment]
We probably could archive it as is but feel that we might as well leave that to one of the last things we do.

**Comment by drvinceknight** [comment]
A note to make sure they get included in the archive: in #30 I've removed the tables for the correlation tables and replaced them with csv files of the data.

**Comment by marcharper** [comment]
Thanks!

**Comment by drvinceknight** [comment]
I've thrown one big archive together and put that in our dropbox folder. Once we're ready to put it on zenodo I'll just put the one tar file there (with explanations etc...).

**Comment by drvinceknight** [comment]
Moran data is all here: https://zenodo.org/record/832285
