### ISSUE TITLE
Draw FSMs

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/axelrod-moran#28]
@Nikoleta-v3 has almost finished this, she just wants to check things.

**Comment by Nikoleta-v3** [comment]
The FSM with a total of 16 states look very complicated. A way to simplify things could be have 
different line colour for `C/C, C/D, D/C, D/D` respectively. 

Not sure if colours would work then because of printing. Just throwing this idea here.

**Comment by drvinceknight** [comment]
> Not sure if colours would work then because of printing. Just throwing this idea here.

I don't think we need it. I think they look fantastic.
