### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/axelrod-moran#46]
How about: "An empirical study of Moran Processes and first impressions in the Iterated Prisoner's Dilemma"?

(Thought of that from your "First impressions matter in the IPD" line in the ml paper @marcharper )

**Comment by drvinceknight** [comment]
What about (to make this and the ml paper a bit of a pair):

> Reinforcement Learning Produces Evolutionary Strong Strategies for the Iterated Prisoner’s Dilemma

**Comment by marcharper** [comment]
- [ ] Reinforcement Learning Produces Invasion Resistant and Cooperative Strategies for the Iterated Prisoner’s Dilemma
- [x] Evolution Reinforces Cooperation with the Emergence of Self-Recognition Mechanisms: an empirical study of the Moran process for the iterated Prisoner's dilemma using reinforcement learning

**Comment by drvinceknight** [comment]
> Evolution Reinforces Cooperation with the Emergence of Self-Recognition Mechanisms: an empirical study of the Moran process for the iterated Prisoner's dilemma using reinforcement learning

Big fan. :+1:
