### ISSUE TITLE
Include heatmap of cooperation rates

### ISSUE THREAD

**Issue by drvinceknight** [Axelrod-Python/axelrod-moran#51]
Would be nice to include images like https://github.com/Axelrod-Python/AxelrodExamples/blob/master/strategies/TF1.md which clearly show the handshake.

These need to be "re run" with the list of players used. Available here: https://github.com/Axelrod-Python/axelrod-moran/blob/master/src/players.py

**Comment by drvinceknight** [comment]
I have this data now being run on the `cooperation_heatmaps` branch.

**Comment by marcharper** [comment]
For the noisy heatmaps the base rate should be at most 95% but the plots in the paper show 100%.
